version: '3'

services:
  web:
    build: .
    image: movies:1.0.0
    container_name: movies-web
    volumes:
      - .:/home/app/movies
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - "db:db"
  db:
    image: postgres:12.13-alpine3.16
    container_name: movies-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=movies_jb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd

volumes:
  postgres_data: